#+TITLE: Generic Instructions 
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: theme-bigblow.setup

* Read and Learn
  Hints and rubrics (how to get points) for each gradebook item are available
  --- come to class to learn how to access them.

  Time Hint: To get maximum time-management benefit, you are encouraged to:
  - track your time for each task (TODO);
  - mark each task DONE when done (type t to toggle its state); and
  - maintain a time-tracking summary report.

  With your cursor on a TODO line, comma I (, I) runs the =org-clock-in=
  command, and comma O (, O) runs the =org-clock-out= command.

  Afterwards, clicking/confirming the link below will insert a table with a
  clock report right below the link. Once inserted, running the link again
  (which can also be done by hitting the Return/Enter key with the cursor in the
  link) will update the table. For your convenience, this link will appear in
  every file.

  [[elisp:(org-clock-report%201)][Insert/Update Clock Summary Report]]

  For example, the bullets below specify two tasks you can practice on. For more
  advice, see the [[file:time-considerations.org][time-considerations.org]] file.

* TODO Reading Assignment 
  Read the textbook\rsquo{}s introductory material (everything before ABC --- which
  means everything up to and including section ONE subsubsection ONI, which ends
  just when subsection ABC begins).

  Take notes, inserting them here.

* TODO Export to See Formatted File
  If you want to see what your file will look like when formatted like The Book,
  run the link below:

  [[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]

  Note that, again for your convenience, one of these links will appear in every
  file.
